/*
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.mert.recherche.MkDslRuntimeModule;
import com.mert.recherche.MkDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MkDslIdeSetup extends MkDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MkDslRuntimeModule(), new MkDslIdeModule()));
	}
	
}
