/*
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MkDslUiModule extends AbstractMkDslUiModule {

	public MkDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
