/*
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMkDslScopeProvider extends DelegatingScopeProvider {
}
