/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ACTION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.ACTION#getName <em>Name</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.ACTION#getID <em>ID</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.ACTION#getEvent <em>Event</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getACTION()
 * @model
 * @generated
 */
public interface ACTION extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getACTION_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.ACTION#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' attribute.
   * @see #setID(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getACTION_ID()
   * @model
   * @generated
   */
  String getID();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.ACTION#getID <em>ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' attribute.
   * @see #getID()
   * @generated
   */
  void setID(String value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' attribute.
   * @see #setEvent(int)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getACTION_Event()
   * @model
   * @generated
   */
  int getEvent();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.ACTION#getEvent <em>Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' attribute.
   * @see #getEvent()
   * @generated
   */
  void setEvent(int value);

} // ACTION
