/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CONDITION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.CONDITION#getName <em>Name</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.CONDITION#getEvals <em>Evals</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getCONDITION()
 * @model
 * @generated
 */
public interface CONDITION extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(int)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getCONDITION_Name()
   * @model
   * @generated
   */
  int getName();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.CONDITION#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(int value);

  /**
   * Returns the value of the '<em><b>Evals</b></em>' containment reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.EVALUABLE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evals</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getCONDITION_Evals()
   * @model containment="true"
   * @generated
   */
  EList<EVALUABLE> getEvals();

} // CONDITION
