/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CONNECTIVE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.CONNECTIVE#getConnective <em>Connective</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getCONNECTIVE()
 * @model
 * @generated
 */
public interface CONNECTIVE extends EVALUABLE
{
  /**
   * Returns the value of the '<em><b>Connective</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connective</em>' attribute.
   * @see #setConnective(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getCONNECTIVE_Connective()
   * @model
   * @generated
   */
  String getConnective();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.CONNECTIVE#getConnective <em>Connective</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connective</em>' attribute.
   * @see #getConnective()
   * @generated
   */
  void setConnective(String value);

} // CONNECTIVE
