/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.DT#getName <em>Name</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.DT#getID <em>ID</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.DT#getConditions <em>Conditions</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.DT#getActions <em>Actions</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.DT#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getDT()
 * @model
 * @generated
 */
public interface DT extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getDT_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.DT#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' attribute.
   * @see #setID(int)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getDT_ID()
   * @model
   * @generated
   */
  int getID();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.DT#getID <em>ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' attribute.
   * @see #getID()
   * @generated
   */
  void setID(int value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.CONDITION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getDT_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<CONDITION> getConditions();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.ACTION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getDT_Actions()
   * @model containment="true"
   * @generated
   */
  EList<ACTION> getActions();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.RULE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getDT_Rules()
   * @model containment="true"
   * @generated
   */
  EList<RULE> getRules();

} // DT
