/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ESG</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.ESG#getName <em>Name</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.ESG#getEvent <em>Event</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.ESG#getSubESGs <em>Sub ES Gs</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.ESG#getEdges <em>Edges</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getESG()
 * @model
 * @generated
 */
public interface ESG extends Declaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getESG_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.ESG#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(Event)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getESG_Event()
   * @model containment="true"
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.ESG#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>Sub ES Gs</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub ES Gs</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getESG_SubESGs()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getSubESGs();

  /**
   * Returns the value of the '<em><b>Edges</b></em>' containment reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.EDGE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edges</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getESG_Edges()
   * @model containment="true"
   * @generated
   */
  EList<EDGE> getEdges();

} // ESG
