/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EXPRESSION</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.EXPRESSION#getLeft <em>Left</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.EXPRESSION#getOperand <em>Operand</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.EXPRESSION#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getEXPRESSION()
 * @model
 * @generated
 */
public interface EXPRESSION extends EVALUABLE
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getEXPRESSION_Left()
   * @model
   * @generated
   */
  String getLeft();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.EXPRESSION#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(String value);

  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference.
   * @see #setOperand(OPERAND)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getEXPRESSION_Operand()
   * @model containment="true"
   * @generated
   */
  OPERAND getOperand();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.EXPRESSION#getOperand <em>Operand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand</em>' containment reference.
   * @see #getOperand()
   * @generated
   */
  void setOperand(OPERAND value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getEXPRESSION_Right()
   * @model
   * @generated
   */
  String getRight();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.EXPRESSION#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(String value);

} // EXPRESSION
