/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.mert.recherche.mkDsl.MkDslPackage
 * @generated
 */
public interface MkDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MkDslFactory eINSTANCE = com.mert.recherche.mkDsl.impl.MkDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declaration</em>'.
   * @generated
   */
  Declaration createDeclaration();

  /**
   * Returns a new object of class '<em>ESG</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ESG</em>'.
   * @generated
   */
  ESG createESG();

  /**
   * Returns a new object of class '<em>VERTEX</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VERTEX</em>'.
   * @generated
   */
  VERTEX createVERTEX();

  /**
   * Returns a new object of class '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event</em>'.
   * @generated
   */
  Event createEvent();

  /**
   * Returns a new object of class '<em>EDGE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EDGE</em>'.
   * @generated
   */
  EDGE createEDGE();

  /**
   * Returns a new object of class '<em>DT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DT</em>'.
   * @generated
   */
  DT createDT();

  /**
   * Returns a new object of class '<em>CONDITION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CONDITION</em>'.
   * @generated
   */
  CONDITION createCONDITION();

  /**
   * Returns a new object of class '<em>RULE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>RULE</em>'.
   * @generated
   */
  RULE createRULE();

  /**
   * Returns a new object of class '<em>ACTION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ACTION</em>'.
   * @generated
   */
  ACTION createACTION();

  /**
   * Returns a new object of class '<em>EVALUABLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EVALUABLE</em>'.
   * @generated
   */
  EVALUABLE createEVALUABLE();

  /**
   * Returns a new object of class '<em>EXPRESSION</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>EXPRESSION</em>'.
   * @generated
   */
  EXPRESSION createEXPRESSION();

  /**
   * Returns a new object of class '<em>CONNECTIVE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CONNECTIVE</em>'.
   * @generated
   */
  CONNECTIVE createCONNECTIVE();

  /**
   * Returns a new object of class '<em>VARIABLE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>VARIABLE</em>'.
   * @generated
   */
  VARIABLE createVARIABLE();

  /**
   * Returns a new object of class '<em>OPERAND</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>OPERAND</em>'.
   * @generated
   */
  OPERAND createOPERAND();

  /**
   * Returns a new object of class '<em>COLOR</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COLOR</em>'.
   * @generated
   */
  COLOR createCOLOR();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MkDslPackage getMkDslPackage();

} //MkDslFactory
