/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.mert.recherche.mkDsl.MkDslFactory
 * @model kind="package"
 * @generated
 */
public interface MkDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mkDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mert.com/recherche/MkDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mkDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MkDslPackage eINSTANCE = com.mert.recherche.mkDsl.impl.MkDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.ModelImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATÝONS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.DeclarationImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATÝON = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATÝON_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.ESGImpl <em>ESG</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.ESGImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getESG()
   * @generated
   */
  int ESG = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESG__NAME = DECLARATÝON_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESG__EVENT = DECLARATÝON_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sub ES Gs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESG__SUB_ES_GS = DECLARATÝON_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Edges</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESG__EDGES = DECLARATÝON_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>ESG</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESG_FEATURE_COUNT = DECLARATÝON_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.VERTEXImpl <em>VERTEX</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.VERTEXImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getVERTEX()
   * @generated
   */
  int VERTEX = 3;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX__ID = 0;

  /**
   * The feature id for the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX__EVENT = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX__COLOR = 2;

  /**
   * The feature id for the '<em><b>Dt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX__DT = 3;

  /**
   * The number of structural features of the '<em>VERTEX</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.EventImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.EDGEImpl <em>EDGE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.EDGEImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEDGE()
   * @generated
   */
  int EDGE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__SOURCE = 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__TARGET = 2;

  /**
   * The feature id for the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE__COLOR = 3;

  /**
   * The number of structural features of the '<em>EDGE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.DTImpl <em>DT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.DTImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getDT()
   * @generated
   */
  int DT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__NAME = 0;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__ID = 1;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__CONDÝTÝONS = 2;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__ACTÝONS = 3;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT__RULES = 4;

  /**
   * The number of structural features of the '<em>DT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.CONDITIONImpl <em>CONDITION</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.CONDITIONImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getCONDITION()
   * @generated
   */
  int CONDITION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Evals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__EVALS = 1;

  /**
   * The number of structural features of the '<em>CONDITION</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.RULEImpl <em>RULE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.RULEImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getRULE()
   * @generated
   */
  int RULE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ID = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__VALUE = 2;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__VARS = 3;

  /**
   * The feature id for the '<em><b>Actions</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__ACTÝONS = 4;

  /**
   * The number of structural features of the '<em>RULE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.ACTIONImpl <em>ACTION</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.ACTIONImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getACTION()
   * @generated
   */
  int ACTION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ID = 1;

  /**
   * The feature id for the '<em><b>Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__EVENT = 2;

  /**
   * The number of structural features of the '<em>ACTION</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.EVALUABLEImpl <em>EVALUABLE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.EVALUABLEImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEVALUABLE()
   * @generated
   */
  int EVALUABLE = 10;

  /**
   * The number of structural features of the '<em>EVALUABLE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVALUABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.EXPRESSIONImpl <em>EXPRESSION</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.EXPRESSIONImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEXPRESSION()
   * @generated
   */
  int EXPRESSION = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = EVALUABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OPERAND = EVALUABLE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RÝGHT = EVALUABLE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>EXPRESSION</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = EVALUABLE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.CONNECTIVEImpl <em>CONNECTIVE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.CONNECTIVEImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getCONNECTIVE()
   * @generated
   */
  int CONNECTIVE = 12;

  /**
   * The feature id for the '<em><b>Connective</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTIVE__CONNECTÝVE = EVALUABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>CONNECTIVE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTIVE_FEATURE_COUNT = EVALUABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.VARIABLEImpl <em>VARIABLE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.VARIABLEImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getVARIABLE()
   * @generated
   */
  int VARIABLE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VALUE = 1;

  /**
   * The number of structural features of the '<em>VARIABLE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.OPERANDImpl <em>OPERAND</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.OPERANDImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getOPERAND()
   * @generated
   */
  int OPERAND = 14;

  /**
   * The feature id for the '<em><b>Operand</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND__OPERAND = 0;

  /**
   * The number of structural features of the '<em>OPERAND</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.mert.recherche.mkDsl.impl.COLORImpl <em>COLOR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.mert.recherche.mkDsl.impl.COLORImpl
   * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getCOLOR()
   * @generated
   */
  int COLOR = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR__NAME = 0;

  /**
   * The number of structural features of the '<em>COLOR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.mert.recherche.mkDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see com.mert.recherche.mkDsl.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see com.mert.recherche.mkDsl.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.ESG <em>ESG</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ESG</em>'.
   * @see com.mert.recherche.mkDsl.ESG
   * @generated
   */
  EClass getESG();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.ESG#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.ESG#getName()
   * @see #getESG()
   * @generated
   */
  EAttribute getESG_Name();

  /**
   * Returns the meta object for the containment reference '{@link com.mert.recherche.mkDsl.ESG#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event</em>'.
   * @see com.mert.recherche.mkDsl.ESG#getEvent()
   * @see #getESG()
   * @generated
   */
  EReference getESG_Event();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.ESG#getSubESGs <em>Sub ES Gs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub ES Gs</em>'.
   * @see com.mert.recherche.mkDsl.ESG#getSubESGs()
   * @see #getESG()
   * @generated
   */
  EReference getESG_SubESGs();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.ESG#getEdges <em>Edges</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Edges</em>'.
   * @see com.mert.recherche.mkDsl.ESG#getEdges()
   * @see #getESG()
   * @generated
   */
  EReference getESG_Edges();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.VERTEX <em>VERTEX</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>VERTEX</em>'.
   * @see com.mert.recherche.mkDsl.VERTEX
   * @generated
   */
  EClass getVERTEX();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.VERTEX#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see com.mert.recherche.mkDsl.VERTEX#getID()
   * @see #getVERTEX()
   * @generated
   */
  EAttribute getVERTEX_ID();

  /**
   * Returns the meta object for the containment reference '{@link com.mert.recherche.mkDsl.VERTEX#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event</em>'.
   * @see com.mert.recherche.mkDsl.VERTEX#getEvent()
   * @see #getVERTEX()
   * @generated
   */
  EReference getVERTEX_Event();

  /**
   * Returns the meta object for the containment reference '{@link com.mert.recherche.mkDsl.VERTEX#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Color</em>'.
   * @see com.mert.recherche.mkDsl.VERTEX#getColor()
   * @see #getVERTEX()
   * @generated
   */
  EReference getVERTEX_Color();

  /**
   * Returns the meta object for the containment reference '{@link com.mert.recherche.mkDsl.VERTEX#getDt <em>Dt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dt</em>'.
   * @see com.mert.recherche.mkDsl.VERTEX#getDt()
   * @see #getVERTEX()
   * @generated
   */
  EReference getVERTEX_Dt();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see com.mert.recherche.mkDsl.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.EDGE <em>EDGE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EDGE</em>'.
   * @see com.mert.recherche.mkDsl.EDGE
   * @generated
   */
  EClass getEDGE();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.EDGE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.EDGE#getName()
   * @see #getEDGE()
   * @generated
   */
  EAttribute getEDGE_Name();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.EDGE#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see com.mert.recherche.mkDsl.EDGE#getSource()
   * @see #getEDGE()
   * @generated
   */
  EAttribute getEDGE_Source();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.EDGE#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see com.mert.recherche.mkDsl.EDGE#getTarget()
   * @see #getEDGE()
   * @generated
   */
  EAttribute getEDGE_Target();

  /**
   * Returns the meta object for the containment reference '{@link com.mert.recherche.mkDsl.EDGE#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Color</em>'.
   * @see com.mert.recherche.mkDsl.EDGE#getColor()
   * @see #getEDGE()
   * @generated
   */
  EReference getEDGE_Color();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.DT <em>DT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DT</em>'.
   * @see com.mert.recherche.mkDsl.DT
   * @generated
   */
  EClass getDT();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.DT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.DT#getName()
   * @see #getDT()
   * @generated
   */
  EAttribute getDT_Name();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.DT#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see com.mert.recherche.mkDsl.DT#getID()
   * @see #getDT()
   * @generated
   */
  EAttribute getDT_ID();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.DT#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see com.mert.recherche.mkDsl.DT#getConditions()
   * @see #getDT()
   * @generated
   */
  EReference getDT_Conditions();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.DT#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see com.mert.recherche.mkDsl.DT#getActions()
   * @see #getDT()
   * @generated
   */
  EReference getDT_Actions();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.DT#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see com.mert.recherche.mkDsl.DT#getRules()
   * @see #getDT()
   * @generated
   */
  EReference getDT_Rules();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.CONDITION <em>CONDITION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CONDITION</em>'.
   * @see com.mert.recherche.mkDsl.CONDITION
   * @generated
   */
  EClass getCONDITION();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.CONDITION#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.CONDITION#getName()
   * @see #getCONDITION()
   * @generated
   */
  EAttribute getCONDITION_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.CONDITION#getEvals <em>Evals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Evals</em>'.
   * @see com.mert.recherche.mkDsl.CONDITION#getEvals()
   * @see #getCONDITION()
   * @generated
   */
  EReference getCONDITION_Evals();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.RULE <em>RULE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>RULE</em>'.
   * @see com.mert.recherche.mkDsl.RULE
   * @generated
   */
  EClass getRULE();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.RULE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.RULE#getName()
   * @see #getRULE()
   * @generated
   */
  EAttribute getRULE_Name();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.RULE#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see com.mert.recherche.mkDsl.RULE#getID()
   * @see #getRULE()
   * @generated
   */
  EAttribute getRULE_ID();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.RULE#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.mert.recherche.mkDsl.RULE#getValue()
   * @see #getRULE()
   * @generated
   */
  EAttribute getRULE_Value();

  /**
   * Returns the meta object for the containment reference list '{@link com.mert.recherche.mkDsl.RULE#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see com.mert.recherche.mkDsl.RULE#getVars()
   * @see #getRULE()
   * @generated
   */
  EReference getRULE_Vars();

  /**
   * Returns the meta object for the reference list '{@link com.mert.recherche.mkDsl.RULE#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Actions</em>'.
   * @see com.mert.recherche.mkDsl.RULE#getActions()
   * @see #getRULE()
   * @generated
   */
  EReference getRULE_Actions();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.ACTION <em>ACTION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ACTION</em>'.
   * @see com.mert.recherche.mkDsl.ACTION
   * @generated
   */
  EClass getACTION();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.ACTION#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.ACTION#getName()
   * @see #getACTION()
   * @generated
   */
  EAttribute getACTION_Name();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.ACTION#getID <em>ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>ID</em>'.
   * @see com.mert.recherche.mkDsl.ACTION#getID()
   * @see #getACTION()
   * @generated
   */
  EAttribute getACTION_ID();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.ACTION#getEvent <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Event</em>'.
   * @see com.mert.recherche.mkDsl.ACTION#getEvent()
   * @see #getACTION()
   * @generated
   */
  EAttribute getACTION_Event();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.EVALUABLE <em>EVALUABLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EVALUABLE</em>'.
   * @see com.mert.recherche.mkDsl.EVALUABLE
   * @generated
   */
  EClass getEVALUABLE();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.EXPRESSION <em>EXPRESSION</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EXPRESSION</em>'.
   * @see com.mert.recherche.mkDsl.EXPRESSION
   * @generated
   */
  EClass getEXPRESSION();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.EXPRESSION#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see com.mert.recherche.mkDsl.EXPRESSION#getLeft()
   * @see #getEXPRESSION()
   * @generated
   */
  EAttribute getEXPRESSION_Left();

  /**
   * Returns the meta object for the containment reference '{@link com.mert.recherche.mkDsl.EXPRESSION#getOperand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operand</em>'.
   * @see com.mert.recherche.mkDsl.EXPRESSION#getOperand()
   * @see #getEXPRESSION()
   * @generated
   */
  EReference getEXPRESSION_Operand();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.EXPRESSION#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see com.mert.recherche.mkDsl.EXPRESSION#getRight()
   * @see #getEXPRESSION()
   * @generated
   */
  EAttribute getEXPRESSION_Right();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.CONNECTIVE <em>CONNECTIVE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>CONNECTIVE</em>'.
   * @see com.mert.recherche.mkDsl.CONNECTIVE
   * @generated
   */
  EClass getCONNECTIVE();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.CONNECTIVE#getConnective <em>Connective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Connective</em>'.
   * @see com.mert.recherche.mkDsl.CONNECTIVE#getConnective()
   * @see #getCONNECTIVE()
   * @generated
   */
  EAttribute getCONNECTIVE_Connective();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.VARIABLE <em>VARIABLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>VARIABLE</em>'.
   * @see com.mert.recherche.mkDsl.VARIABLE
   * @generated
   */
  EClass getVARIABLE();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.VARIABLE#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.VARIABLE#getName()
   * @see #getVARIABLE()
   * @generated
   */
  EAttribute getVARIABLE_Name();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.VARIABLE#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.mert.recherche.mkDsl.VARIABLE#getValue()
   * @see #getVARIABLE()
   * @generated
   */
  EAttribute getVARIABLE_Value();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.OPERAND <em>OPERAND</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>OPERAND</em>'.
   * @see com.mert.recherche.mkDsl.OPERAND
   * @generated
   */
  EClass getOPERAND();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.OPERAND#getOperand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operand</em>'.
   * @see com.mert.recherche.mkDsl.OPERAND#getOperand()
   * @see #getOPERAND()
   * @generated
   */
  EAttribute getOPERAND_Operand();

  /**
   * Returns the meta object for class '{@link com.mert.recherche.mkDsl.COLOR <em>COLOR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COLOR</em>'.
   * @see com.mert.recherche.mkDsl.COLOR
   * @generated
   */
  EClass getCOLOR();

  /**
   * Returns the meta object for the attribute '{@link com.mert.recherche.mkDsl.COLOR#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.mert.recherche.mkDsl.COLOR#getName()
   * @see #getCOLOR()
   * @generated
   */
  EAttribute getCOLOR_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MkDslFactory getMkDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.ModelImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATÝONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.DeclarationImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATÝON = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.ESGImpl <em>ESG</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.ESGImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getESG()
     * @generated
     */
    EClass ESG = eINSTANCE.getESG();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ESG__NAME = eINSTANCE.getESG_Name();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESG__EVENT = eINSTANCE.getESG_Event();

    /**
     * The meta object literal for the '<em><b>Sub ES Gs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESG__SUB_ES_GS = eINSTANCE.getESG_SubESGs();

    /**
     * The meta object literal for the '<em><b>Edges</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ESG__EDGES = eINSTANCE.getESG_Edges();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.VERTEXImpl <em>VERTEX</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.VERTEXImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getVERTEX()
     * @generated
     */
    EClass VERTEX = eINSTANCE.getVERTEX();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX__ID = eINSTANCE.getVERTEX_ID();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX__EVENT = eINSTANCE.getVERTEX_Event();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX__COLOR = eINSTANCE.getVERTEX_Color();

    /**
     * The meta object literal for the '<em><b>Dt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX__DT = eINSTANCE.getVERTEX_Dt();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.EventImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.EDGEImpl <em>EDGE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.EDGEImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEDGE()
     * @generated
     */
    EClass EDGE = eINSTANCE.getEDGE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE__NAME = eINSTANCE.getEDGE_Name();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE__SOURCE = eINSTANCE.getEDGE_Source();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE__TARGET = eINSTANCE.getEDGE_Target();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE__COLOR = eINSTANCE.getEDGE_Color();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.DTImpl <em>DT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.DTImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getDT()
     * @generated
     */
    EClass DT = eINSTANCE.getDT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DT__NAME = eINSTANCE.getDT_Name();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DT__ID = eINSTANCE.getDT_ID();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DT__CONDÝTÝONS = eINSTANCE.getDT_Conditions();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DT__ACTÝONS = eINSTANCE.getDT_Actions();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DT__RULES = eINSTANCE.getDT_Rules();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.CONDITIONImpl <em>CONDITION</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.CONDITIONImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getCONDITION()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCONDITION();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getCONDITION_Name();

    /**
     * The meta object literal for the '<em><b>Evals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__EVALS = eINSTANCE.getCONDITION_Evals();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.RULEImpl <em>RULE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.RULEImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getRULE()
     * @generated
     */
    EClass RULE = eINSTANCE.getRULE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__NAME = eINSTANCE.getRULE_Name();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__ID = eINSTANCE.getRULE_ID();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__VALUE = eINSTANCE.getRULE_Value();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__VARS = eINSTANCE.getRULE_Vars();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__ACTÝONS = eINSTANCE.getRULE_Actions();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.ACTIONImpl <em>ACTION</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.ACTIONImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getACTION()
     * @generated
     */
    EClass ACTION = eINSTANCE.getACTION();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getACTION_Name();

    /**
     * The meta object literal for the '<em><b>ID</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ID = eINSTANCE.getACTION_ID();

    /**
     * The meta object literal for the '<em><b>Event</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__EVENT = eINSTANCE.getACTION_Event();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.EVALUABLEImpl <em>EVALUABLE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.EVALUABLEImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEVALUABLE()
     * @generated
     */
    EClass EVALUABLE = eINSTANCE.getEVALUABLE();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.EXPRESSIONImpl <em>EXPRESSION</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.EXPRESSIONImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getEXPRESSION()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getEXPRESSION();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__LEFT = eINSTANCE.getEXPRESSION_Left();

    /**
     * The meta object literal for the '<em><b>Operand</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__OPERAND = eINSTANCE.getEXPRESSION_Operand();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__RÝGHT = eINSTANCE.getEXPRESSION_Right();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.CONNECTIVEImpl <em>CONNECTIVE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.CONNECTIVEImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getCONNECTIVE()
     * @generated
     */
    EClass CONNECTIVE = eINSTANCE.getCONNECTIVE();

    /**
     * The meta object literal for the '<em><b>Connective</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTIVE__CONNECTÝVE = eINSTANCE.getCONNECTIVE_Connective();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.VARIABLEImpl <em>VARIABLE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.VARIABLEImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getVARIABLE()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVARIABLE();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVARIABLE_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__VALUE = eINSTANCE.getVARIABLE_Value();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.OPERANDImpl <em>OPERAND</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.OPERANDImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getOPERAND()
     * @generated
     */
    EClass OPERAND = eINSTANCE.getOPERAND();

    /**
     * The meta object literal for the '<em><b>Operand</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERAND__OPERAND = eINSTANCE.getOPERAND_Operand();

    /**
     * The meta object literal for the '{@link com.mert.recherche.mkDsl.impl.COLORImpl <em>COLOR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.mert.recherche.mkDsl.impl.COLORImpl
     * @see com.mert.recherche.mkDsl.impl.MkDslPackageImpl#getCOLOR()
     * @generated
     */
    EClass COLOR = eINSTANCE.getCOLOR();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR__NAME = eINSTANCE.getCOLOR_Name();

  }

} //MkDslPackage
