/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>RULE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.RULE#getName <em>Name</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.RULE#getID <em>ID</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.RULE#getValue <em>Value</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.RULE#getVars <em>Vars</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.RULE#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getRULE()
 * @model
 * @generated
 */
public interface RULE extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getRULE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.RULE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' attribute.
   * @see #setID(int)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getRULE_ID()
   * @model
   * @generated
   */
  int getID();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.RULE#getID <em>ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' attribute.
   * @see #getID()
   * @generated
   */
  void setID(int value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getRULE_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.RULE#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Vars</b></em>' containment reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.VARIABLE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' containment reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getRULE_Vars()
   * @model containment="true"
   * @generated
   */
  EList<VARIABLE> getVars();

  /**
   * Returns the value of the '<em><b>Actions</b></em>' reference list.
   * The list contents are of type {@link com.mert.recherche.mkDsl.ACTION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' reference list.
   * @see com.mert.recherche.mkDsl.MkDslPackage#getRULE_Actions()
   * @model
   * @generated
   */
  EList<ACTION> getActions();

} // RULE
