/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VERTEX</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.mert.recherche.mkDsl.VERTEX#getID <em>ID</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.VERTEX#getEvent <em>Event</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.VERTEX#getColor <em>Color</em>}</li>
 *   <li>{@link com.mert.recherche.mkDsl.VERTEX#getDt <em>Dt</em>}</li>
 * </ul>
 *
 * @see com.mert.recherche.mkDsl.MkDslPackage#getVERTEX()
 * @model
 * @generated
 */
public interface VERTEX extends EObject
{
  /**
   * Returns the value of the '<em><b>ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>ID</em>' attribute.
   * @see #setID(String)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getVERTEX_ID()
   * @model
   * @generated
   */
  String getID();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.VERTEX#getID <em>ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ID</em>' attribute.
   * @see #getID()
   * @generated
   */
  void setID(String value);

  /**
   * Returns the value of the '<em><b>Event</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event</em>' containment reference.
   * @see #setEvent(Event)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getVERTEX_Event()
   * @model containment="true"
   * @generated
   */
  Event getEvent();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.VERTEX#getEvent <em>Event</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event</em>' containment reference.
   * @see #getEvent()
   * @generated
   */
  void setEvent(Event value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' containment reference.
   * @see #setColor(COLOR)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getVERTEX_Color()
   * @model containment="true"
   * @generated
   */
  COLOR getColor();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.VERTEX#getColor <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' containment reference.
   * @see #getColor()
   * @generated
   */
  void setColor(COLOR value);

  /**
   * Returns the value of the '<em><b>Dt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dt</em>' containment reference.
   * @see #setDt(DT)
   * @see com.mert.recherche.mkDsl.MkDslPackage#getVERTEX_Dt()
   * @model containment="true"
   * @generated
   */
  DT getDt();

  /**
   * Sets the value of the '{@link com.mert.recherche.mkDsl.VERTEX#getDt <em>Dt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dt</em>' containment reference.
   * @see #getDt()
   * @generated
   */
  void setDt(DT value);

} // VERTEX
