/**
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.mkDsl.impl;

import com.mert.recherche.mkDsl.EVALUABLE;
import com.mert.recherche.mkDsl.MkDslPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EVALUABLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EVALUABLEImpl extends MinimalEObjectImpl.Container implements EVALUABLE
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EVALUABLEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MkDslPackage.Literals.EVALUABLE;
  }

} //EVALUABLEImpl
