/*
 * generated by Xtext 2.25.0
 */
package com.mert.recherche.parser.antlr;

import com.google.inject.Inject;
import com.mert.recherche.parser.antlr.internal.InternalMkDslParser;
import com.mert.recherche.services.MkDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MkDslParser extends AbstractAntlrParser {

	@Inject
	private MkDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMkDslParser createParser(XtextTokenStream stream) {
		return new InternalMkDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MkDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MkDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
