/*
 * generated by Xtext 2.25.0
 */
package com.mert.recherche;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MkDslStandaloneSetup extends MkDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MkDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
