/*
 * generated by Xtext 2.25.0
 */
package com.mert.recherche;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MkDslRuntimeModule extends AbstractMkDslRuntimeModule {
}
